"""
JavaScript Date builtin module.

Usage:
    import pulse.js.date as Date
    Date.now()                    # -> Date.now()
    Date.parse("2023-01-01")      # -> Date.parse("2023-01-01")

    from pulse.js.date import now, parse
    now()                         # -> Date.now()
    parse("2023-01-01")           # -> Date.parse("2023-01-01")
"""

from __future__ import annotations

from typing import Protocol

from pulse.transpiler.js_module import register_js_module


class Date(Protocol):
	"""Protocol for JavaScript Date instances."""

	def __init__(self, value: int | str | None = None): ...

	def getDate(self) -> int: ...
	def getDay(self) -> int: ...
	def getFullYear(self) -> int: ...
	def getHours(self) -> int: ...
	def getMilliseconds(self) -> int: ...
	def getMinutes(self) -> int: ...
	def getMonth(self) -> int: ...
	def getSeconds(self) -> int: ...
	def getTime(self) -> float: ...
	def getTimezoneOffset(self) -> int: ...
	def getUTCDate(self) -> int: ...
	def getUTCDay(self) -> int: ...
	def getUTCFullYear(self) -> int: ...
	def getUTCHours(self) -> int: ...
	def getUTCMilliseconds(self) -> int: ...
	def getUTCMinutes(self) -> int: ...
	def getUTCMonth(self) -> int: ...
	def getUTCSeconds(self) -> int: ...
	def setDate(self, date: int) -> float: ...
	def setFullYear(
		self, year: int, month: int | None = None, date: int | None = None
	) -> float: ...
	def setHours(
		self,
		hours: int,
		min: int | None = None,
		sec: int | None = None,
		ms: int | None = None,
	) -> float: ...
	def setMilliseconds(self, ms: int) -> float: ...
	def setMinutes(
		self, min: int, sec: int | None = None, ms: int | None = None
	) -> float: ...
	def setMonth(self, month: int, date: int | None = None) -> float: ...
	def setSeconds(self, sec: int, ms: int | None = None) -> float: ...
	def setTime(self, time: float) -> float: ...
	def setUTCDate(self, date: int) -> float: ...
	def setUTCFullYear(
		self, year: int, month: int | None = None, date: int | None = None
	) -> float: ...
	def setUTCHours(
		self,
		hours: int,
		min: int | None = None,
		sec: int | None = None,
		ms: int | None = None,
	) -> float: ...
	def setUTCMilliseconds(self, ms: int) -> float: ...
	def setUTCMinutes(
		self, min: int, sec: int | None = None, ms: int | None = None
	) -> float: ...
	def setUTCMonth(self, month: int, date: int | None = None) -> float: ...
	def setUTCSeconds(self, sec: int, ms: int | None = None) -> float: ...
	def toDateString(self) -> str: ...
	def toISOString(self) -> str: ...
	def toJSON(self, key: object | None = None) -> str: ...
	def toLocaleDateString(
		self, locales: str | None = None, options: object | None = None
	) -> str: ...
	def toLocaleString(
		self, locales: str | None = None, options: object | None = None
	) -> str: ...
	def toLocaleTimeString(
		self, locales: str | None = None, options: object | None = None
	) -> str: ...
	def toString(self) -> str: ...
	def toTimeString(self) -> str: ...
	def toUTCString(self) -> str: ...
	def valueOf(self) -> float: ...


# Static Methods (type stubs for IDE support)
def now() -> float: ...
def parse(dateString: str) -> float: ...
def UTC(
	year: int,
	month: int,
	date: int | None = None,
	hours: int | None = None,
	minutes: int | None = None,
	seconds: int | None = None,
	ms: int | None = None,
) -> float: ...


# Self-register this module as a JS builtin
register_js_module(name="Date", global_scope=True)
