"""
JavaScript Object builtin module.

Usage:
    import pulse.js.object as Object
    Object.keys({"a": 1})         # -> Object.keys({"a": 1})
    Object.assign({}, {"a": 1})   # -> Object.assign({}, {"a": 1})
    Object.is(x, y)                # -> Object.is(x, y)

    # Note: For 'is' (Python keyword), use namespace import:
    # import pulse.js.object as Object; Object.is(...)
    # Or use the underscore version for direct import:
    from pulse.js.object import keys, assign, is_
    keys({"a": 1})                # -> Object.keys({"a": 1})
    assign({}, {"a": 1})          # -> Object.assign({}, {"a": 1})
    is_(x, y)                     # -> Object.is(x, y)
"""

from __future__ import annotations

from pulse.transpiler.js_module import register_js_module


# Static Methods (type stubs for IDE support)
def assign(target: object, *sources: object) -> object: ...
def create(proto: object | None, propertiesObject: object | None = None) -> object: ...
def defineProperty(obj: object, prop: str, descriptor: object) -> object: ...
def defineProperties(obj: object, props: object) -> object: ...
def entries(obj: object) -> list[tuple[str, object]]: ...
def freeze(obj: object) -> object: ...
def fromEntries(entries: list[tuple[str, object]]) -> object: ...
def getOwnPropertyDescriptor(obj: object, prop: str) -> object | None: ...
def getOwnPropertyDescriptors(obj: object) -> object: ...
def getOwnPropertyNames(obj: object) -> list[str]: ...
def getOwnPropertySymbols(obj: object) -> list[object]: ...
def getPrototypeOf(obj: object) -> object | None: ...
def hasOwn(obj: object, prop: str) -> bool: ...
def is_(value1: object, value2: object) -> bool: ...
def isExtensible(obj: object) -> bool: ...
def isFrozen(obj: object) -> bool: ...
def isSealed(obj: object) -> bool: ...
def keys(obj: object) -> list[str]: ...
def preventExtensions(obj: object) -> object: ...
def seal(obj: object) -> object: ...
def setPrototypeOf(obj: object, prototype: object | None) -> object: ...
def values(obj: object) -> list[object]: ...


# Self-register this module as a JS builtin
register_js_module(name="Object", global_scope=True)
