"""Shared runtime constants for pulse-railway."""

AFFINITY_QUERY_PARAM = "pulse_deployment"
AFFINITY_HEADER = "x-pulse-deployment"
ACTIVE_DEPLOYMENT_VARIABLE = "PULSE_ACTIVE_DEPLOYMENT"
DEPLOYMENT_META_PATH = "/_pulse/meta"
INTERNAL_API_PREFIX = "/_pulse/internal"
INTERNAL_SESSIONS_PATH = "/_pulse/internal/railway/sessions"
INTERNAL_TOKEN_HEADER = "x-pulse-railway-internal-token"
DEFAULT_BACKEND_HEALTH_PATH = "/_pulse/health"
DEFAULT_BACKEND_PORT = 8000
DEFAULT_DRAIN_GRACE_SECONDS = 60
DEFAULT_JANITOR_INTERVAL_SECONDS = 60
DEFAULT_JANITOR_LOCK_TTL_SECONDS = 55
DEFAULT_MAX_DRAIN_AGE_SECONDS = 24 * 60 * 60
DEFAULT_REDIS_PREFIX = "pulse:railway"
DEFAULT_REDIS_TEMPLATE_CODE = "redis"
DEFAULT_ROUTER_HEALTH_PATH = "/healthz"
DEFAULT_ROUTER_PORT = 8000
DEFAULT_SERVICE_PREFIX = "pulse-"
DEFAULT_WEBSOCKET_HEARTBEAT_SECONDS = 15
DEFAULT_WEBSOCKET_TTL_SECONDS = 45
RAILWAY_API_ENDPOINT = "https://backboard.railway.com/graphql/v2"
RAILWAY_DEPLOYMENT_ID_ENV = "PULSE_RAILWAY_DEPLOYMENT_ID"
RAILWAY_ENVIRONMENT_ID_ENV = "PULSE_RAILWAY_ENVIRONMENT_ID"
RAILWAY_JANITOR_DRAIN_GRACE_SECONDS_ENV = "PULSE_RAILWAY_JANITOR_DRAIN_GRACE_SECONDS"
RAILWAY_JANITOR_INTERVAL_SECONDS_ENV = "PULSE_RAILWAY_JANITOR_INTERVAL_SECONDS"
RAILWAY_JANITOR_MAX_DRAIN_AGE_SECONDS_ENV = (
	"PULSE_RAILWAY_JANITOR_MAX_DRAIN_AGE_SECONDS"
)
RAILWAY_PROJECT_ID_ENV = "PULSE_RAILWAY_PROJECT_ID"
RAILWAY_INTERNAL_TOKEN_ENV = "PULSE_RAILWAY_INTERNAL_TOKEN"
RAILWAY_REDIS_PREFIX_ENV = "PULSE_RAILWAY_REDIS_PREFIX"
RAILWAY_REDIS_URL_ENV = "PULSE_RAILWAY_REDIS_URL"
RAILWAY_SERVICE_PREFIX_ENV = "PULSE_RAILWAY_SERVICE_PREFIX"
RAILWAY_TOKEN_ENV = "PULSE_RAILWAY_TOKEN"
RAILWAY_WEBSOCKET_HEARTBEAT_SECONDS_ENV = "PULSE_RAILWAY_WEBSOCKET_HEARTBEAT_SECONDS"
RAILWAY_WEBSOCKET_TTL_SECONDS_ENV = "PULSE_RAILWAY_WEBSOCKET_TTL_SECONDS"
